# Generated by Django 3.2 on 2024-10-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelFormJugadorApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='equipo',
        ),
        migrations.AddField(
            model_name='jugador',
            name='campeonatos',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jugador',
            name='eficacia',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jugador',
            name='ppp',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jugador',
            name='apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='posicion',
            field=models.CharField(choices=[('base', 'Base'), ('escolta', 'Escolta'), ('alero', 'Alero'), ('ala-pivot', 'Ala-Pivot'), ('pivot', 'Pivot')], max_length=20),
        ),
    ]
