# Generated by Django 3.2 on 2024-10-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelFormJugadorApp', '0002_auto_20241025_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='posicion',
            field=models.CharField(choices=[('Base', 'Base'), ('Escolta', 'Escolta'), ('Alero', 'Alero'), ('Ala-Pivot', 'Ala-Pivot'), ('Pivot', 'Pivot')], max_length=20),
        ),
    ]
